language: generic

sudo: required

dist: trusty

services:
  - docker

install:
  - docker pull lamtev/latex

matrix:
  include:
    - env: LATEX_TEMPLATE="bachelor_thesis"
    - env: LATEX_TEMPLATE="master_thesis"
    - env: LATEX_TEMPLATE="coursework"
    - env: LATEX_TEMPLATE="presentation"
    - env: LATEX_TEMPLATE="report"

script:
  - chmod +x travis_build.sh
  - docker run -v $TRAVIS_BUILD_DIR:/latex_templates lamtev/latex /bin/bash -c " cd latex_templates && . ./travis_build.sh && build_latex_template $LATEX_TEMPLATE "

before_deploy:
  - sudo chmod 777 ${TRAVIS_BUILD_DIR}/${LATEX_TEMPLATE}/${LATEX_TEMPLATE}.pdf

deploy:
  provider: releases
  api_key: "$GITHUB_DEPLOY_TOKEN"
  file: ${TRAVIS_BUILD_DIR}/${LATEX_TEMPLATE}/${LATEX_TEMPLATE}.pdf
  skip_cleanup: true
  on:
    tags: true
